### ISSUE TITLE
Vanilla 1.12.1 compatibility?

### ISSUE THREAD

**Issue by HerrTiSo** [keyboardturner/WoWMapUprezClassic#1]
Hello there, I wondered if this add-on would be technically compatible with older WoW iterations, such as WoW Vanilla 1.12.1 specifically? Thank you for your amazing work, and have a nice day!

**Comment by keyboardturner** [comment]
no plans for vanilla / non-official versions of the game

Edit: made a comment thinking it was a different project, oops.

But yeah I've largely discontinued this project for the time being. I'd rather make it into a full ingame addon, which requires very different API.

Classic should largely work with vanilla, I think? If it doesn't idk what to say though.

**Comment by HerrTiSo** [comment]
Thanks for your quick response. We tried the mod with an 1.12.1 client, but it ends up crashing. Most likely due to file size limits of that old engine. I'll let you know if I'm able to somehow fix it on my end.
